server:
  port: "Fill Thisgit rm --cached filename"       # Порт, на котором будет запускаться сервер

database:
  host: "Fill This"   # Адрес базы данных
  port:   Fill This       # Порт базы данных
  user: "Fill This"    # Имя пользователя базы данных
  password: "Fill This"  # Пароль пользователя базы данных
  dbname: "Fill This"    # Имя базы данных
  sslmode: "disable"
  

#может быть и не нужно это
logger:
  output: "stdout"  # Куда выводить логи: stdout или же file
  filepath: ""      # Путь где будут храниться логи, если выбран output "file"
  level: "debug"     # Уровни логирования: "debug", "info", "warn", "error"

#jwt token string
jwt:
  jwtkey: "Fill This"

migration:
  migrationpath: "./db/migrations" #путь к миграциям
